"""
GET /api/gpx/{request_id}/{rank}

Generates a GPX file on-the-fly from the in-memory route geometry stored in
the session cache. This avoids needing a finalized DB route record.

The route geometry is stored in a simple in-memory dict keyed by
"{request_id}-{rank}" after each generate-full call. Entries expire after
2 hours to avoid unbounded memory growth.
"""

import logging
import time
from typing import Optional

from fastapi import APIRouter, HTTPException
from fastapi.responses import Response

logger = logging.getLogger(__name__)
router = APIRouter()

# In-memory cache: key = "{request_id}-{rank}", value = {"coords": [...], "meta": {...}, "ts": float}
_ROUTE_CACHE: dict = {}
_CACHE_TTL = 7200  # 2 hours


def store_route_geometry(route_id: str, coords: list, meta: dict):
    """Store route geometry for later GPX download. Called from generate_full."""
    _ROUTE_CACHE[route_id] = {
        "coords": coords,  # list of [lat, lon]
        "meta": meta,
        "ts": time.time(),
    }
    # Evict entries older than TTL
    now = time.time()
    expired = [k for k, v in _ROUTE_CACHE.items() if now - v["ts"] > _CACHE_TTL]
    for k in expired:
        del _ROUTE_CACHE[k]


def get_cached_route(route_id: str) -> Optional[dict]:
    entry = _ROUTE_CACHE.get(route_id)
    if entry and (time.time() - entry["ts"]) < _CACHE_TTL:
        return entry
    return None


@router.get("/gpx/{route_id}")
def download_gpx(route_id: str):
    """
    Generate and return a GPX file for a route generated by /api/generate-full.
    route_id is in the format "{request_uuid}-{rank}".
    """
    entry = get_cached_route(route_id)
    if not entry:
        raise HTTPException(
            status_code=404,
            detail="Route not found or expired. Please generate the route again.",
        )

    try:
        import gpxpy
        import gpxpy.gpx
    except ImportError:
        raise HTTPException(status_code=500, detail="gpxpy not installed")

    coords = entry["coords"]  # [[lat, lon], ...]
    meta = entry["meta"]

    gpx = gpxpy.gpx.GPX()
    gpx.name = meta.get("trip_title", f"Bikepacking Route {route_id}")
    gpx.description = (
        f"{meta.get('total_distance_km', 0):.0f} km, "
        f"{meta.get('total_climbing_m', 0):.0f} m climbing, "
        f"{meta.get('gravel_ratio', 0) * 100:.0f}% gravel"
    )

    track = gpxpy.gpx.GPXTrack()
    track.name = gpx.name
    gpx.tracks.append(track)

    segment = gpxpy.gpx.GPXTrackSegment()
    track.segments.append(segment)

    for lat, lon in coords:
        segment.points.append(gpxpy.gpx.GPXTrackPoint(latitude=lat, longitude=lon))

    # Add overnight waypoints if available
    for i, overnight in enumerate(meta.get("overnight_areas", []), 1):
        coords_ov = overnight.get("coordinates")
        if coords_ov and len(coords_ov) == 2:
            lat_ov, lon_ov = coords_ov
            wpt = gpxpy.gpx.GPXWaypoint(
                latitude=lat_ov,
                longitude=lon_ov,
                name=overnight.get("name", f"Night {i}"),
                description=overnight.get("description", ""),
            )
            gpx.waypoints.append(wpt)

    content = gpx.to_xml()
    filename = meta.get("trip_title", f"bikepacking_{route_id}").replace(" ", "_")[:50]

    return Response(
        content=content,
        media_type="application/gpx+xml",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}.gpx"'
        },
    )
