"""
POST /api/rwgps/export/{route_id}
Pushes a generated route to RideWithGPS using Basic Auth (API key + auth token).
This uses the account configured in Railway env vars (RWGPS_API_KEY + RWGPS_AUTH_TOKEN).
For per-user OAuth, this endpoint should be replaced with an OAuth flow in a future version.
"""
import logging
import requests
from fastapi import APIRouter, HTTPException

from backend.config import settings
from backend.api.gpx_inline import get_cached_route

logger = logging.getLogger(__name__)
router = APIRouter()

RWGPS_BASE = "https://ridewithgps.com"


def _build_track_points(coords: list) -> list:
    """Convert [[lat, lon], ...] to RWGPS track_points format."""
    return [
        {"x": lon, "y": lat, "d": i * 10}  # x=lon, y=lat, d=distance offset (approx)
        for i, (lat, lon) in enumerate(coords)
    ]


@router.post("/rwgps/export/{route_id}")
def export_to_rwgps(route_id: str):
    """
    Push a cached route to RideWithGPS.
    Returns the RideWithGPS route URL on success.
    """
    if not settings.rwgps_api_key or not settings.rwgps_auth_token:
        raise HTTPException(
            status_code=503,
            detail="RideWithGPS credentials not configured. Set RWGPS_API_KEY and RWGPS_AUTH_TOKEN in environment variables.",
        )

    entry = get_cached_route(route_id)
    if not entry:
        raise HTTPException(
            status_code=404,
            detail="Route not found or expired. Please generate the route again.",
        )

    coords = entry["coords"]  # [[lat, lon], ...]
    meta = entry["meta"]

    trip_title = meta.get("trip_title", f"Bikepacking Route {route_id}")
    total_km = meta.get("total_distance_km", 0)
    total_climb = meta.get("total_climbing_m", 0)
    gravel_pct = int(meta.get("gravel_ratio", 0) * 100)

    description = (
        f"{total_km:.0f} km · {total_climb:.0f} m climbing · {gravel_pct}% gravel\n"
        f"Generated by Bikepacker AI"
    )

    track_points = _build_track_points(coords)

    payload = {
        "apikey": settings.rwgps_api_key,
        "version": "2",
        "auth_token": settings.rwgps_auth_token,
        "route": {
            "name": trip_title,
            "description": description,
            "track_points": track_points,
            "is_stationary": False,
        },
    }

    try:
        resp = requests.post(
            f"{RWGPS_BASE}/routes.json",
            json=payload,
            timeout=20,
        )
    except requests.RequestException as e:
        logger.error("RideWithGPS request failed: %s", e)
        raise HTTPException(status_code=502, detail=f"RideWithGPS request failed: {e}")

    if resp.status_code not in (200, 201):
        logger.error("RideWithGPS error %s: %s", resp.status_code, resp.text[:300])
        raise HTTPException(
            status_code=502,
            detail=f"RideWithGPS returned {resp.status_code}: {resp.text[:200]}",
        )

    try:
        data = resp.json()
        route_id_rwgps = data.get("route", {}).get("id") or data.get("id")
        if route_id_rwgps:
            rwgps_url = f"https://ridewithgps.com/routes/{route_id_rwgps}"
        else:
            rwgps_url = "https://ridewithgps.com/routes"
    except Exception:
        rwgps_url = "https://ridewithgps.com/routes"

    return {"success": True, "url": rwgps_url}
