"""
SQLAlchemy ORM models.

Geometry is no longer stored in the database — routes are generated on-the-fly
by Mapbox Directions API and returned directly to the frontend as GeoJSON.
The database stores trip metadata, parsed specs, and finalized route summaries.
"""

import datetime
from sqlalchemy import (
    BigInteger, Boolean, Column, DateTime, Float, Index, Integer,
    JSON, String, Text, ForeignKey
)
from sqlalchemy.orm import DeclarativeBase, relationship


class Base(DeclarativeBase):
    pass


class TripRequest(Base):
    """Stores raw prompts and their parsed trip specs."""
    __tablename__ = "trip_requests"

    id = Column(String, primary_key=True)  # UUID string
    raw_prompt = Column(Text, nullable=False)
    parsed_constraints_json = Column(JSON, nullable=True)
    rider_profile_json = Column(JSON, nullable=True)
    region = Column(String(64), nullable=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)

    candidate_routes = relationship("CandidateRoute", back_populates="trip_request")
    final_routes = relationship("FinalRoute", back_populates="trip_request")


class CandidateRoute(Base):
    """A fully assembled candidate route with metrics and scores."""
    __tablename__ = "candidate_routes"

    id = Column(Integer, primary_key=True, autoincrement=True)
    request_id = Column(String, ForeignKey("trip_requests.id"), nullable=False, index=True)
    # Route geometry stored as GeoJSON string (generated by Mapbox, not PostGIS)
    geometry_geojson = Column(Text, nullable=True)
    total_distance_km = Column(Float, nullable=True)
    total_climbing_m = Column(Float, nullable=True)
    gravel_ratio = Column(Float, nullable=True)
    paved_ratio = Column(Float, nullable=True)
    overnight_plan_json = Column(JSON, nullable=True)
    route_metrics_json = Column(JSON, nullable=True)
    score_breakdown_json = Column(JSON, nullable=True)
    status = Column(String(32), nullable=False, default="pending")

    trip_request = relationship("TripRequest", back_populates="candidate_routes")
    final_route = relationship("FinalRoute", back_populates="candidate_route", uselist=False)


class FinalRoute(Base):
    """A finalized route selected by the user."""
    __tablename__ = "final_routes"

    id = Column(Integer, primary_key=True, autoincrement=True)
    request_id = Column(String, ForeignKey("trip_requests.id"), nullable=False, index=True)
    candidate_route_id = Column(Integer, ForeignKey("candidate_routes.id"), nullable=False)
    gpx_blob_path = Column(String(512), nullable=True)
    final_summary_json = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow, nullable=False)

    trip_request = relationship("TripRequest", back_populates="final_routes")
    candidate_route = relationship("CandidateRoute", back_populates="final_route")
