"""
Pydantic schemas for route candidates and finalized routes.
"""

from datetime import datetime
from typing import Any, Literal, Optional
from pydantic import BaseModel, Field

from .poi import OvernightStop


class RouteMetrics(BaseModel):
    """Computed metrics for a candidate route."""
    total_distance_km: float
    total_climbing_m: float
    total_descending_m: float
    gravel_ratio: float
    paved_ratio: float
    uncertain_km: float
    hike_a_bike_km: float
    per_day_distance_km: list[float]
    per_day_climbing_m: list[float]
    traffic_score_avg: float
    scenic_score_avg: float
    data_quality_score_avg: float


class ScoreBreakdown(BaseModel):
    """
    Soft scoring breakdown across 11 dimensions.
    Each dimension is 0.0–1.0. weighted_total is the aggregated score.
    """
    distance_fit: float = Field(ge=0.0, le=1.0)
    daily_effort_fit: float = Field(ge=0.0, le=1.0)
    climbing_fit: float = Field(ge=0.0, le=1.0)
    surface_fit: float = Field(ge=0.0, le=1.0)
    rider_fit: float = Field(ge=0.0, le=1.0)
    overnight_quality: float = Field(ge=0.0, le=1.0)
    logistics_fit: float = Field(ge=0.0, le=1.0)
    traffic_comfort: float = Field(ge=0.0, le=1.0)
    scenic_value: float = Field(ge=0.0, le=1.0)
    uncertainty_confidence: float = Field(ge=0.0, le=1.0)
    loop_quality: float = Field(ge=0.0, le=1.0)
    weighted_total: float = Field(ge=0.0, le=1.0)


class RelaxationRecord(BaseModel):
    """Records one step of constraint relaxation that was applied."""
    step: int
    dimension: str
    original_value: Any
    relaxed_value: Any
    reason: str


class CandidateRoute(BaseModel):
    """
    A fully assembled route candidate with metrics, scores, and overnight plan.
    geometry is a GeoJSON LineString of the full route.
    """
    id: Optional[int] = None
    request_id: str
    geometry: dict[str, Any]  # GeoJSON LineString
    metrics: RouteMetrics
    overnight_plan: list[OvernightStop]
    score_breakdown: Optional[ScoreBreakdown] = None
    passed_hard_filters: bool = False
    filter_failures: list[str] = Field(default_factory=list)
    relaxations_applied: list[RelaxationRecord] = Field(default_factory=list)
    status: Literal["pending", "filtered", "scored", "selected", "rejected"] = "pending"


class RouteSummary(BaseModel):
    """Human-readable summary for display, generated by Claude."""
    headline: str
    body: str
    warnings: list[str] = Field(default_factory=list)


class FinalRoute(BaseModel):
    """A finalized route ready for GPX export and display."""
    id: Optional[int] = None
    request_id: str
    candidate_route_id: int
    route: CandidateRoute
    summary: RouteSummary
    gpx_available: bool = False
    created_at: Optional[datetime] = None


class GenerateRequest(BaseModel):
    """Request body for POST /api/generate."""
    request_id: str


class GenerateResponse(BaseModel):
    """Response from POST /api/generate."""
    request_id: str
    candidates: list[CandidateRoute]
    relaxations_applied: list[RelaxationRecord] = Field(default_factory=list)
    no_results_reason: Optional[str] = None


class FinalizeRequest(BaseModel):
    """Request body for POST /api/finalize."""
    request_id: str
    candidate_route_id: int


class FinalizeResponse(BaseModel):
    """Response from POST /api/finalize."""
    route_id: int
    summary: RouteSummary
    gpx_download_url: str
